#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
/* automatically generated by rust-bindgen 0.72.1 */

pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __WORDSIZE: u32 = 64;
pub const __has_safe_buffers: u32 = 1;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_ONLY_VERS_1050: u32 = 1;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_EXTSN: &[u8; 14] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
pub const __STDC_WANT_LIB_EXT1__: u32 = 1;
pub const __DARWIN_NO_LONG_LONG: u32 = 0;
pub const _DARWIN_FEATURE_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_VERS_1050: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: u32 = 3;
pub const __has_ptrcheck: u32 = 0;
pub const __has_bounds_safety_attributes: u32 = 0;
pub const USE_CLANG_TYPES: u32 = 0;
pub const __PTHREAD_SIZE__: u32 = 8176;
pub const __PTHREAD_ATTR_SIZE__: u32 = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: u32 = 8;
pub const __PTHREAD_MUTEX_SIZE__: u32 = 56;
pub const __PTHREAD_CONDATTR_SIZE__: u32 = 8;
pub const __PTHREAD_COND_SIZE__: u32 = 40;
pub const __PTHREAD_ONCE_SIZE__: u32 = 8;
pub const __PTHREAD_RWLOCK_SIZE__: u32 = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: u32 = 16;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -32768;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 32767;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 65535;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const UINTPTR_MAX: i32 = -1;
pub const SIZE_MAX: i32 = -1;
pub const RSIZE_MAX: i32 = -1;
pub const WINT_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const ARM64_TMP_REG_NDX_0: u32 = 17;
pub const RT_FAILED: i32 = -1;
pub const RT_SUCCESS: u32 = 0;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: ::std::os::raw::c_longlong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t"][::std::mem::size_of::<__mbstate_t>() - 128usize];
    ["Alignment of __mbstate_t"][::std::mem::align_of::<__mbstate_t>() - 8usize];
    ["Offset of field: __mbstate_t::__mbstate8"]
        [::std::mem::offset_of!(__mbstate_t, __mbstate8) - 0usize];
    ["Offset of field: __mbstate_t::_mbstateL"]
        [::std::mem::offset_of!(__mbstate_t, _mbstateL) - 0usize];
};
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __darwin_pthread_handler_rec"]
        [::std::mem::size_of::<__darwin_pthread_handler_rec>() - 24usize];
    ["Alignment of __darwin_pthread_handler_rec"]
        [::std::mem::align_of::<__darwin_pthread_handler_rec>() - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__routine"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __routine) - 0usize];
    ["Offset of field: __darwin_pthread_handler_rec::__arg"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __arg) - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__next"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_attr_t"][::std::mem::size_of::<_opaque_pthread_attr_t>() - 64usize];
    ["Alignment of _opaque_pthread_attr_t"]
        [::std::mem::align_of::<_opaque_pthread_attr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_attr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_attr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_cond_t"][::std::mem::size_of::<_opaque_pthread_cond_t>() - 48usize];
    ["Alignment of _opaque_pthread_cond_t"]
        [::std::mem::align_of::<_opaque_pthread_cond_t>() - 8usize];
    ["Offset of field: _opaque_pthread_cond_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_cond_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_condattr_t"]
        [::std::mem::size_of::<_opaque_pthread_condattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_condattr_t"]
        [::std::mem::align_of::<_opaque_pthread_condattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_condattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_condattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutex_t"][::std::mem::size_of::<_opaque_pthread_mutex_t>() - 64usize];
    ["Alignment of _opaque_pthread_mutex_t"]
        [::std::mem::align_of::<_opaque_pthread_mutex_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutex_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutex_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutexattr_t"]
        [::std::mem::size_of::<_opaque_pthread_mutexattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_mutexattr_t"]
        [::std::mem::align_of::<_opaque_pthread_mutexattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_once_t"][::std::mem::size_of::<_opaque_pthread_once_t>() - 16usize];
    ["Alignment of _opaque_pthread_once_t"]
        [::std::mem::align_of::<_opaque_pthread_once_t>() - 8usize];
    ["Offset of field: _opaque_pthread_once_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_once_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlock_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlock_t>() - 200usize];
    ["Alignment of _opaque_pthread_rwlock_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlock_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlockattr_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlockattr_t>() - 24usize];
    ["Alignment of _opaque_pthread_rwlockattr_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlockattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_t"][::std::mem::size_of::<_opaque_pthread_t>() - 8192usize];
    ["Alignment of _opaque_pthread_t"][::std::mem::align_of::<_opaque_pthread_t>() - 8usize];
    ["Offset of field: _opaque_pthread_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_t::__cleanup_stack"]
        [::std::mem::offset_of!(_opaque_pthread_t, __cleanup_stack) - 8usize];
    ["Offset of field: _opaque_pthread_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_t, __opaque) - 16usize];
};
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
unsafe extern "C" {
    pub fn log_set_level(level: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn log_switch_to_syslog();
}
unsafe extern "C" {
    pub fn log_switch_to_file(path: *const ::std::os::raw::c_char);
}
pub const MemoryOperationError_kMemoryOperationSuccess: MemoryOperationError = 0;
pub const MemoryOperationError_kMemoryOperationError: MemoryOperationError = 1;
pub const MemoryOperationError_kNotSupportAllocateExecutableMemory: MemoryOperationError = 2;
pub const MemoryOperationError_kNotEnough: MemoryOperationError = 3;
pub const MemoryOperationError_kNone: MemoryOperationError = 4;
pub type MemoryOperationError = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn CodePatch(
        address: *mut ::std::os::raw::c_void,
        buffer: *mut u8,
        buffer_size: u32,
    ) -> MemoryOperationError;
}
pub type addr_t = usize;
pub type addr32_t = u32;
pub type addr64_t = u64;
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union _FPReg {
    pub q: _FPReg___int128_t,
    pub d: _FPReg__bindgen_ty_1,
    pub f: _FPReg__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FPReg__bindgen_ty_1 {
    pub d1: f64,
    pub d2: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FPReg__bindgen_ty_1"][::std::mem::size_of::<_FPReg__bindgen_ty_1>() - 16usize];
    ["Alignment of _FPReg__bindgen_ty_1"][::std::mem::align_of::<_FPReg__bindgen_ty_1>() - 8usize];
    ["Offset of field: _FPReg__bindgen_ty_1::d1"]
        [::std::mem::offset_of!(_FPReg__bindgen_ty_1, d1) - 0usize];
    ["Offset of field: _FPReg__bindgen_ty_1::d2"]
        [::std::mem::offset_of!(_FPReg__bindgen_ty_1, d2) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FPReg__bindgen_ty_2 {
    pub f1: f32,
    pub f2: f32,
    pub f3: f32,
    pub f4: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FPReg__bindgen_ty_2"][::std::mem::size_of::<_FPReg__bindgen_ty_2>() - 16usize];
    ["Alignment of _FPReg__bindgen_ty_2"][::std::mem::align_of::<_FPReg__bindgen_ty_2>() - 4usize];
    ["Offset of field: _FPReg__bindgen_ty_2::f1"]
        [::std::mem::offset_of!(_FPReg__bindgen_ty_2, f1) - 0usize];
    ["Offset of field: _FPReg__bindgen_ty_2::f2"]
        [::std::mem::offset_of!(_FPReg__bindgen_ty_2, f2) - 4usize];
    ["Offset of field: _FPReg__bindgen_ty_2::f3"]
        [::std::mem::offset_of!(_FPReg__bindgen_ty_2, f3) - 8usize];
    ["Offset of field: _FPReg__bindgen_ty_2::f4"]
        [::std::mem::offset_of!(_FPReg__bindgen_ty_2, f4) - 12usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _FPReg"][::std::mem::size_of::<_FPReg>() - 16usize];
    ["Alignment of _FPReg"][::std::mem::align_of::<_FPReg>() - 16usize];
    ["Offset of field: _FPReg::q"][::std::mem::offset_of!(_FPReg, q) - 0usize];
    ["Offset of field: _FPReg::d"][::std::mem::offset_of!(_FPReg, d) - 0usize];
    ["Offset of field: _FPReg::f"][::std::mem::offset_of!(_FPReg, f) - 0usize];
};
pub type FPReg = _FPReg;
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct _RegisterContext {
    pub dmmpy_0: u64,
    pub sp: u64,
    pub dmmpy_1: u64,
    pub general: _RegisterContext__bindgen_ty_1,
    pub fp: u64,
    pub lr: u64,
    pub floating: _RegisterContext__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _RegisterContext__bindgen_ty_1 {
    pub x: [u64; 29usize],
    pub regs: _RegisterContext__bindgen_ty_1__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _RegisterContext__bindgen_ty_1__bindgen_ty_1 {
    pub x0: u64,
    pub x1: u64,
    pub x2: u64,
    pub x3: u64,
    pub x4: u64,
    pub x5: u64,
    pub x6: u64,
    pub x7: u64,
    pub x8: u64,
    pub x9: u64,
    pub x10: u64,
    pub x11: u64,
    pub x12: u64,
    pub x13: u64,
    pub x14: u64,
    pub x15: u64,
    pub x16: u64,
    pub x17: u64,
    pub x18: u64,
    pub x19: u64,
    pub x20: u64,
    pub x21: u64,
    pub x22: u64,
    pub x23: u64,
    pub x24: u64,
    pub x25: u64,
    pub x26: u64,
    pub x27: u64,
    pub x28: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _RegisterContext__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<_RegisterContext__bindgen_ty_1__bindgen_ty_1>() - 232usize];
    ["Alignment of _RegisterContext__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<_RegisterContext__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x0"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x0) - 0usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x1"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x1) - 8usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x2"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x2) - 16usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x3"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x3) - 24usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x4"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x4) - 32usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x5"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x5) - 40usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x6"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x6) - 48usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x7"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x7) - 56usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x8"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x8) - 64usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x9"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x9) - 72usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x10"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x10) - 80usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x11"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x11) - 88usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x12"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x12) - 96usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x13"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x13) - 104usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x14"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x14) - 112usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x15"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x15) - 120usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x16"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x16) - 128usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x17"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x17) - 136usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x18"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x18) - 144usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x19"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x19) - 152usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x20"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x20) - 160usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x21"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x21) - 168usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x22"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x22) - 176usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x23"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x23) - 184usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x24"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x24) - 192usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x25"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x25) - 200usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x26"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x26) - 208usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x27"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x27) - 216usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1__bindgen_ty_1::x28"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1__bindgen_ty_1, x28) - 224usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _RegisterContext__bindgen_ty_1"]
        [::std::mem::size_of::<_RegisterContext__bindgen_ty_1>() - 232usize];
    ["Alignment of _RegisterContext__bindgen_ty_1"]
        [::std::mem::align_of::<_RegisterContext__bindgen_ty_1>() - 8usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1::x"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1, x) - 0usize];
    ["Offset of field: _RegisterContext__bindgen_ty_1::regs"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_1, regs) - 0usize];
};
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub union _RegisterContext__bindgen_ty_2 {
    pub q: [FPReg; 32usize],
    pub regs: _RegisterContext__bindgen_ty_2__bindgen_ty_1,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Copy, Clone)]
pub struct _RegisterContext__bindgen_ty_2__bindgen_ty_1 {
    pub q0: FPReg,
    pub q1: FPReg,
    pub q2: FPReg,
    pub q3: FPReg,
    pub q4: FPReg,
    pub q5: FPReg,
    pub q6: FPReg,
    pub q7: FPReg,
    pub q8: FPReg,
    pub q9: FPReg,
    pub q10: FPReg,
    pub q11: FPReg,
    pub q12: FPReg,
    pub q13: FPReg,
    pub q14: FPReg,
    pub q15: FPReg,
    pub q16: FPReg,
    pub q17: FPReg,
    pub q18: FPReg,
    pub q19: FPReg,
    pub q20: FPReg,
    pub q21: FPReg,
    pub q22: FPReg,
    pub q23: FPReg,
    pub q24: FPReg,
    pub q25: FPReg,
    pub q26: FPReg,
    pub q27: FPReg,
    pub q28: FPReg,
    pub q29: FPReg,
    pub q30: FPReg,
    pub q31: FPReg,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _RegisterContext__bindgen_ty_2__bindgen_ty_1"]
        [::std::mem::size_of::<_RegisterContext__bindgen_ty_2__bindgen_ty_1>() - 512usize];
    ["Alignment of _RegisterContext__bindgen_ty_2__bindgen_ty_1"]
        [::std::mem::align_of::<_RegisterContext__bindgen_ty_2__bindgen_ty_1>() - 16usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q0"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q0) - 0usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q1"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q1) - 16usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q2"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q2) - 32usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q3"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q3) - 48usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q4"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q4) - 64usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q5"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q5) - 80usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q6"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q6) - 96usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q7"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q7) - 112usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q8"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q8) - 128usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q9"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q9) - 144usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q10"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q10) - 160usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q11"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q11) - 176usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q12"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q12) - 192usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q13"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q13) - 208usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q14"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q14) - 224usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q15"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q15) - 240usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q16"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q16) - 256usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q17"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q17) - 272usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q18"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q18) - 288usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q19"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q19) - 304usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q20"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q20) - 320usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q21"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q21) - 336usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q22"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q22) - 352usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q23"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q23) - 368usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q24"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q24) - 384usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q25"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q25) - 400usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q26"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q26) - 416usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q27"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q27) - 432usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q28"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q28) - 448usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q29"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q29) - 464usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q30"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q30) - 480usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2__bindgen_ty_1::q31"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2__bindgen_ty_1, q31) - 496usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _RegisterContext__bindgen_ty_2"]
        [::std::mem::size_of::<_RegisterContext__bindgen_ty_2>() - 512usize];
    ["Alignment of _RegisterContext__bindgen_ty_2"]
        [::std::mem::align_of::<_RegisterContext__bindgen_ty_2>() - 16usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2::q"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2, q) - 0usize];
    ["Offset of field: _RegisterContext__bindgen_ty_2::regs"]
        [::std::mem::offset_of!(_RegisterContext__bindgen_ty_2, regs) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _RegisterContext"][::std::mem::size_of::<_RegisterContext>() - 784usize];
    ["Alignment of _RegisterContext"][::std::mem::align_of::<_RegisterContext>() - 16usize];
    ["Offset of field: _RegisterContext::dmmpy_0"]
        [::std::mem::offset_of!(_RegisterContext, dmmpy_0) - 0usize];
    ["Offset of field: _RegisterContext::sp"]
        [::std::mem::offset_of!(_RegisterContext, sp) - 8usize];
    ["Offset of field: _RegisterContext::dmmpy_1"]
        [::std::mem::offset_of!(_RegisterContext, dmmpy_1) - 16usize];
    ["Offset of field: _RegisterContext::general"]
        [::std::mem::offset_of!(_RegisterContext, general) - 24usize];
    ["Offset of field: _RegisterContext::fp"]
        [::std::mem::offset_of!(_RegisterContext, fp) - 256usize];
    ["Offset of field: _RegisterContext::lr"]
        [::std::mem::offset_of!(_RegisterContext, lr) - 264usize];
    ["Offset of field: _RegisterContext::floating"]
        [::std::mem::offset_of!(_RegisterContext, floating) - 272usize];
};
pub type RegisterContext = _RegisterContext;
pub const _RetStatus_RS_FAILED: _RetStatus = -1;
pub const _RetStatus_RS_SUCCESS: _RetStatus = 0;
pub type _RetStatus = ::std::os::raw::c_int;
pub use self::_RetStatus as RetStatus;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _HookEntryInfo {
    pub hook_id: ::std::os::raw::c_int,
    pub __bindgen_anon_1: _HookEntryInfo__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _HookEntryInfo__bindgen_ty_1 {
    pub target_address: *mut ::std::os::raw::c_void,
    pub function_address: *mut ::std::os::raw::c_void,
    pub instruction_address: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _HookEntryInfo__bindgen_ty_1"]
        [::std::mem::size_of::<_HookEntryInfo__bindgen_ty_1>() - 8usize];
    ["Alignment of _HookEntryInfo__bindgen_ty_1"]
        [::std::mem::align_of::<_HookEntryInfo__bindgen_ty_1>() - 8usize];
    ["Offset of field: _HookEntryInfo__bindgen_ty_1::target_address"]
        [::std::mem::offset_of!(_HookEntryInfo__bindgen_ty_1, target_address) - 0usize];
    ["Offset of field: _HookEntryInfo__bindgen_ty_1::function_address"]
        [::std::mem::offset_of!(_HookEntryInfo__bindgen_ty_1, function_address) - 0usize];
    ["Offset of field: _HookEntryInfo__bindgen_ty_1::instruction_address"]
        [::std::mem::offset_of!(_HookEntryInfo__bindgen_ty_1, instruction_address) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _HookEntryInfo"][::std::mem::size_of::<_HookEntryInfo>() - 16usize];
    ["Alignment of _HookEntryInfo"][::std::mem::align_of::<_HookEntryInfo>() - 8usize];
    ["Offset of field: _HookEntryInfo::hook_id"]
        [::std::mem::offset_of!(_HookEntryInfo, hook_id) - 0usize];
};
pub type HookEntryInfo = _HookEntryInfo;
unsafe extern "C" {
    pub fn DobbyBuildVersion() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn DobbyHook(
        address: *mut ::std::os::raw::c_void,
        replace_call: *mut ::std::os::raw::c_void,
        origin_call: *mut *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
pub type DBICallTy = ::std::option::Option<
    unsafe extern "C" fn(ctx: *mut RegisterContext, info: *const HookEntryInfo),
>;
unsafe extern "C" {
    pub fn DobbyInstrument(
        address: *mut ::std::os::raw::c_void,
        dbi_call: DBICallTy,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn DobbyDestroy(address: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn DobbySymbolResolver(
        image_name: *const ::std::os::raw::c_char,
        symbol_name: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn DobbyGlobalOffsetTableReplace(
        image_name: *mut ::std::os::raw::c_char,
        symbol_name: *mut ::std::os::raw::c_char,
        fake_func: *mut ::std::os::raw::c_void,
        orig_func: *mut *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn dobby_enable_near_branch_trampoline();
}
unsafe extern "C" {
    pub fn dobby_disable_near_branch_trampoline();
}
pub type linker_load_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        image_name: *const ::std::os::raw::c_char,
        handle: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn dobby_register_image_load_callback(func: linker_load_callback_t);
}
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
pub type _FPReg___int128_t = i128;
